---
- name: Helm | Ensure keyrings dir exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Helm | Download Helm GPG key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /tmp/helm-signing.asc
    mode: "0644"
  become: true

- name: Helm | Dearmor key
  ansible.builtin.command: >
    gpg --dearmor -o /etc/apt/keyrings/helm.gpg /tmp/helm-signing.asc
  args:
    creates: /etc/apt/keyrings/helm.gpg
  become: true

- name: Helm | Compute apt arch
  ansible.builtin.set_fact:
    apt_arch: >-
      {{ 'amd64' if ansible_architecture in ['x86_64'] else
         'arm64' if ansible_architecture in ['aarch64','arm64'] else ansible_architecture }}

- name: Helm | Add repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ apt_arch }} signed-by=/etc/apt/keyrings/helm.gpg]
      https://baltocdn.com/helm/stable/debian/ all main
    filename: helm-stable-debian
    mode: "0644"
    state: present
  become: true

- name: Helm | Install Helm
  ansible.builtin.apt:
    name: helm
    update_cache: true
    state: present
  become: true
