---
# =====================================================================
# Role: zsh
# Installs and configures Z shell depending on the environment.
# =====================================================================

- name: "Include OS-specific tasks"
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "ubuntu.yml"
        - "wsl.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/tasks"
