---
- name: Install zsh on Ubuntu
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true

- name: Ensure zsh is default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true
