---
- name: "Ensure zsh is installed in WSL"
  become: true
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true

- name: "Set zsh as default shell inside WSL"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  when: ansible_user_shell != "/usr/bin/zsh"
