---
- name: "PowerShell | Ensure keyrings dir exists"
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: "PowerShell | Download Microsoft key"
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    dest: "/tmp/microsoft.asc"
    mode: "0644"
  become: true

- name: "PowerShell | Dearmor Microsoft key"
  ansible.builtin.command: >
    gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg /tmp/microsoft.asc
  args:
    creates: /etc/apt/keyrings/microsoft.gpg
  become: true

- name: "PowerShell | Compute apt arch"
  ansible.builtin.set_fact:
    apt_arch: >-
      {{ 'amd64' if ansible_architecture in ['x86_64'] else
         'arm64' if ansible_architecture in ['aarch64','arm64'] else ansible_architecture }}

- name: "PowerShell | Add repository"
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ apt_arch }} signed-by=/etc/apt/keyrings/microsoft.gpg]
      https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_lsb.codename }} main
    filename: microsoft-prod
    mode: "0644"
    state: present
  become: true

- name: "PowerShell | Install powershell"
  ansible.builtin.apt:
    name: powershell
    update_cache: true
    state: present
  become: true
