---
# Compute to_install and to_remove from apps_desired vs ansible_local.installed_apps

- name: Load current and desired sets
  ansible.builtin.set_fact:
    current_apps: "{{ (ansible_local.installed_apps.apps | default([])) }}"
    desired_apps: "{{ apps_desired | default([]) }}"

- name: Helper ID sets
  ansible.builtin.set_fact:
    current_ids: "{{ current_apps | map(attribute='id') | list }}"
    desired_ids: "{{ desired_apps | map(attribute='id') | list }}"

- name: Compute plan
  ansible.builtin.set_fact:
    to_install: "{{ desired_apps | rejectattr('id','in', current_ids) | list }}"
    to_remove:  "{{ current_apps  | rejectattr('id','in', desired_ids) | list }}"

- name: Emit plan (for audit)
  ansible.builtin.copy:
    dest: /var/log/dotfiles/apps_plan.json
    content: "{{ {'to_install': to_install, 'to_remove': to_remove} | to_nice_json }}"
    mode: "0644"
  become: true
