---
# Ensure a local fact at /etc/ansible/facts.d/installed_apps.fact (JSON)

- name: Ensure facts.d exists
  become: true
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"

- name: Seed registry if missing
  become: true
  ansible.builtin.copy:
    dest: /etc/ansible/facts.d/installed_apps.fact
    content: '{"apps":[]}'
    mode: "0644"
  when: ansible_local.installed_apps is not defined

- name: Refresh local facts (installed_apps)
  ansible.builtin.setup:
    filter: ansible_local
