---
- name: Gather Ubuntu version
  ansible.builtin.setup:
    filter: ansible_distribution_version
  register: ubuntu_version

- name: Ensure curl is installed
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Install Starship via apt if Ubuntu >= 25.04
  apt:
    name: starship
    state: present
  when: ubuntu_version.ansible_facts.ansible_distribution_version is version('25.04', '>=')

- name: Download and install Starship
  ansible.builtin.shell: |
    curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship # Prevent re-running if Starship is already installed

- name: Configure Bash to use Starship (if using Bash)
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'eval "$(starship init bash)"'
    insertafter: EOF
    state: present
    backup: yes
  when: ansible_facts['env']['SHELL'] == '/bin/bash'

- name: Configure Zsh to use Starship (if using Zsh)
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'eval "$(starship init zsh)"'
    insertafter: EOF
    state: present
    backup: yes
  when: ansible_facts['env']['SHELL'] == '/bin/zsh'

- name: Ensure Fish config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: directory
    mode: '0755'

- name: Configure Fish to use Starship (if using Fish)
  ansible.builtin.lineinfile:
    path: ~/.config/fish/config.fish
    line: 'starship init fish | source'
    insertafter: EOF
    state: present
    backup: yes
  when: ansible_facts['env']['SHELL'] == '/usr/bin/fish' # Adjust path if necessary

- name: Ensure ~/.config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'
    
- name: Render Starship config
  ansible.builtin.template:
    src: starship.toml.j2
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(1000) }}"
    mode: "0644"
