---
# Self-hosted Vaultwarden (Linux only by default).
# Installs Docker, Python docker SDK, and reconciles the container.

- name: Fail early if not Linux
  ansible.builtin.assert:
    that: ansible_facts.os_family in ['Debian','RedHat','Archlinux','Suse']
    fail_msg: "vault_vaultwarden role is supported on Linux only by default."
  tags: [vault, vault_vaultwarden]

# Engine packages
- name: Debian/Ubuntu | Engine pre-reqs
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-pip
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts.os_family == 'Debian'
  tags: [vault, vault_vaultwarden]

- name: Fedora/RHEL | Engine pre-reqs
  ansible.builtin.dnf:
    name:
      - docker
      - python3-pip
    state: present
  when: ansible_facts.os_family == 'RedHat'
  tags: [vault, vault_vaultwarden]

- name: Arch | Engine pre-reqs
  community.general.pacman:
    name:
      - docker
      - python-pip
    state: present
    update_cache: true
  when: ansible_facts.os_family == 'Archlinux'
  tags: [vault, vault_vaultwarden]

- name: openSUSE | Engine pre-reqs
  community.general.zypper:
    name:
      - docker
      - python3-pip
    state: present
  when: ansible_facts.os_family == 'Suse'
  tags: [vault, vault_vaultwarden]

# Python SDK for docker modules
- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
    state: present
    executable: pip3
  tags: [vault, vault_vaultwarden]

# Service
- name: Ensure Docker service enabled & running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  tags: [vault, vault_vaultwarden]

# Data dir
- name: Ensure Vaultwarden data directory
  ansible.builtin.file:
    path: "{{ vaultwarden_data_dir }}"
    owner: root
    group: root
    mode: "0750"
    state: directory
  tags: [vault, vault_vaultwarden]

# Container
- name: Run Vaultwarden container
  community.docker.docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    pull: true
    restart_policy: unless-stopped
    ports:
      - "127.0.0.1:{{ vaultwarden_port }}:80"
    volumes:
      - "{{ vaultwarden_data_dir }}:/data"
    env:
      SIGNUPS_ALLOWED: "{{ vaultwarden_signups_allowed | string }}"
      DOMAIN: "{{ vaultwarden_domain }}"
  tags: [vault, vault_vaultwarden]
