---
# Example custom uninstall hook for KeepassXC

- name: macOS | Uninstall KeepassXC cask
  when:
    - ansible_facts.os_family == 'Darwin'
    - app.source == 'cask'
  community.general.homebrew_cask:
    name: keepassxc
    state: absent

- name: macOS | Remove KeepassXC support files
  when: ansible_facts.os_family == 'Darwin'
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ lookup('env','HOME') }}/Library/Application Support/KeePassXC"
    - "{{ lookup('env','HOME') }}/Library/Preferences/org.keepassx.keepassxc.plist"
