---
- name: Ensure user fonts dir
  file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: "0755"
  become: false

- name: Download JetBrainsMono Nerd Font (latest)
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
    dest: /tmp/JetBrainsMonoNerd.zip
    mode: "0644"
  become: false

- name: Unzip fonts
  unarchive:
    src: /tmp/JetBrainsMonoNerd.zip
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: true
  become: false

- name: Refresh font cache
  command: fc-cache -f
  changed_when: false
